# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'weather_app.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtWidgets
from PyQt5.QtGui import *

class Ui_Dialog(object):

    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1111, 767)
        self.button_NL = QtWidgets.QPushButton(Dialog)
        self.button_NL.setGeometry(QtCore.QRect(40, 40, 171, 41))
        self.button_NL.setStyleSheet("background-color: rgb(85, 85, 127);\n"
"color: rgb(255, 255, 255);")
        self.button_NL.setObjectName("button_NL")
        self.button_NL.setFont(QFont("Arial", 11))
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(630, 130, 371, 41))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit.setFont(QFont("Arial", 14))
        self.button_weather = QtWidgets.QPushButton(Dialog)
        self.button_weather.setGeometry(QtCore.QRect(630, 190, 371, 31))
        self.button_weather.setStyleSheet("background-color: rgb(85, 85, 127);\n"
"color: rgb(255, 255, 255);")
        self.button_weather.setObjectName("button_weather")
        self.button_weather.setFont(QFont("Arial", 10))
        self.label_title = QtWidgets.QLabel(Dialog)
        self.label_title.setGeometry(QtCore.QRect(630, 70, 371, 31))
        self.label_title.setStyleSheet(
"font: 63 14pt \"Yu Gothic UI Semibold\";")
        self.label_title.setObjectName("label_title")
        self.label_title.setAlignment(QtCore.Qt.AlignCenter)
        self.label_city = QtWidgets.QLabel(Dialog)
        self.label_city.setGeometry(QtCore.QRect(631, 261, 120, 23))
        self.label_city.setStyleSheet("font: 63 14pt \"Yu Gothic UI Semibold\";\n"
"color: rgb(0,0,0);")
        self.label_city.setObjectName("label_city")
        self.label_province = QtWidgets.QLabel(Dialog)
        self.label_province.setGeometry(QtCore.QRect(631, 313, 120, 23))
        self.label_province.setStyleSheet("font: 63 14pt \"Yu Gothic UI Semibold\";\n"
"color: rgb(0,0,0);")
        self.label_province.setObjectName("label_province")
        self.label_population = QtWidgets.QLabel(Dialog)
        self.label_population.setGeometry(QtCore.QRect(631, 365, 140, 23))
        self.label_population.setStyleSheet("font: 63 14pt \"Yu Gothic UI Semibold\";")
        self.label_population.setObjectName("label_population")
        self.label_sel_city = QtWidgets.QLabel(Dialog)
        self.label_sel_city.setGeometry(QtCore.QRect(835, 261, 220, 30))
        self.label_sel_city.setStyleSheet("font: 63 14pt \"Yu Gothic UI Semibold\";")
        self.label_sel_city.setObjectName("label_sel_city")
        self.label_sel_province = QtWidgets.QLabel(Dialog)
        self.label_sel_province.setGeometry(QtCore.QRect(835, 313, 220, 30))
        self.label_sel_province.setStyleSheet("font: 63 14pt \"Yu Gothic UI Semibold\";")
        self.label_sel_province.setObjectName("label_sel_province")
        self.label_sel_population = QtWidgets.QLabel(Dialog)
        self.label_sel_population.setGeometry(QtCore.QRect(835, 365, 220, 23))
        self.label_sel_population.setStyleSheet("font: 63 14pt \"Yu Gothic UI Semibold\";")
        self.label_sel_population.setObjectName("label_sel_population")
        self.label_temp = QtWidgets.QLabel(Dialog)
        self.label_temp.setGeometry(QtCore.QRect(630, 550, 371, 91))
        self.label_temp.setAlignment(QtCore.Qt.AlignCenter)
        self.label_temp.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 63 28pt \"Yu Gothic UI Semibold\";\n"
"")
        self.label_temp.setObjectName("label_temp")
        self.label_population_3 = QtWidgets.QLabel(Dialog)
        self.label_population_3.setGeometry(QtCore.QRect(630, 660, 371, 61))
        self.label_population_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_population_3.setStyleSheet("color : rgb(255, 255, 255);\n"
"font: 63 14pt \"Yu Gothic UI Semibold\";\n"
"")
        self.label_population_3.setObjectName("label_population_3")
        self.label_background = QtWidgets.QLabel(Dialog)
        self.label_background.setGeometry(QtCore.QRect(0, 0, 1111, 771))
        self.label_background.setMinimumSize(QtCore.QSize(1111, 771))
        self.label_background.setMaximumSize(QtCore.QSize(1111, 771))
        self.label_background.setTabletTracking(True)
        self.label_background.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_background.setStyleSheet("background-image: url(C:/Users/merve/VSCODE INFOTECHACADEMY/WEATHER/background/x.jpg);\n"
"")
        self.label_background.setText("")
        self.label_background.setObjectName("label_background")
        self.label_icon = QtWidgets.QLabel(Dialog)
        self.label_icon.setGeometry(QtCore.QRect(630, 450, 371, 91))
        self.label_icon.setAlignment(QtCore.Qt.AlignCenter)
        self.label_icon.setStyleSheet("font: 63 20pt \"Yu Gothic UI Semibold\";")
        self.label_icon.setObjectName("label_icon")
        self.button_USA = QtWidgets.QPushButton(Dialog)
        self.button_USA.setGeometry(QtCore.QRect(210, 40, 161, 41))
        self.button_USA.setStyleSheet("background-color: rgb(85, 85, 127);\n"
"color: rgb(255, 255, 255);")
        self.button_USA.setObjectName("button_USA")
        self.button_USA.setFont(QFont("Arial", 11))
        self.button_DE = QtWidgets.QPushButton(Dialog)
        self.button_DE.setGeometry(QtCore.QRect(370, 40, 161, 41))
        self.button_DE.setStyleSheet("background-color: rgb(85, 85, 127);\n"
"color: rgb(255, 255, 255);")
        self.button_DE.setObjectName("button_TR")
        self.button_DE.setFont(QFont("Arial", 11))
        self.tableWidget = QtWidgets.QTableWidget(Dialog)
        self.tableWidget.setGeometry(QtCore.QRect(40, 100, 491, 631))
        self.tableWidget.setStyleSheet("background-color: transparent;\n"
                                       "font: 63 10pt \"Yu Gothic UI Semibold\";\n")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(1)
        
        self.tableWidget.setColumnWidth(0,160)
        self.tableWidget.setColumnWidth(1,160)
        self.tableWidget.setColumnWidth(2,160)

        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        self.label_background.raise_()
        self.tableWidget.raise_()
        self.button_NL.raise_()
        self.lineEdit.raise_()
        self.button_weather.raise_()
        self.label_title.raise_()
        self.label_city.raise_()
        self.label_province.raise_()
        self.label_population.raise_()
        self.label_sel_city.raise_()
        self.label_sel_province.raise_()
        self.label_sel_population.raise_()
        self.label_temp.raise_()
        self.label_population_3.raise_()
        self.label_icon.raise_()
        self.button_USA.raise_()
        self.button_DE.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "WEATHER_app"))
        self.button_NL.setText(_translate("Dialog", "NL"))
        self.button_weather.setText(_translate("Dialog", "WEATHER"))
        self.label_title.setText(_translate("Dialog", "CITY"))
        self.label_city.setText(_translate("Dialog", "CITY"))
        self.label_province.setText(_translate("Dialog", "PROVINCE"))
        self.label_population.setText(_translate("Dialog", "POPULATION"))
        self.label_sel_city.setText(_translate("Dialog", "-"))
        self.label_sel_province.setText(_translate("Dialog", "-"))
        self.label_sel_population.setText(_translate("Dialog", "-"))
        self.label_temp.setText(_translate("Dialog", " "))
        self.label_population_3.setText(_translate("Dialog", " "))
        self.label_icon.setText(_translate("Dialog", " "))
        self.button_USA.setText(_translate("Dialog", "USA"))
        self.button_DE.setText(_translate("Dialog", "DE"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("Dialog", "1"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "CITY"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "PROVINCE"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "POPULATION"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
